---
title: "A definition of faith"
description: ""
date: "2025-11-15"
categories: [epistemology, critical-thinking, faith, models]
---

The word *faith* can mean many things to many people. My purpose here is to propose a precise definition for what faith is drawing on writings from The Church of Jesus Christ of Latter-Day Saints. While the source material is religious in nature, the definition that I propose is applicable in any domain of life by anyone, regardless of their individual belief system.

Faith consists of two distinct but related dimensions:

1. Belief
2. Action

Both belief or action exist on a spectrum bounded by none and perfect. 

Having 


The word *faith* can mean many things to many people and has various definitions. 

For me, faith is something that every person on the planet has even if they don't call it that. 

For me, faith is simply acting in accordance with a belief you have which happens to be true.

Unpacking that, faith has three distinct facets: belief, action, truth.

It's common to think someone has faith just because they believe something. 



Have you 



One of the best insights about faith